課題②完了
tamaji22/JavaScript_task2-1 pull request #1
Opened 2020-11-19 11:22 UTC by tamaji22

JavaScrit課題②が完了しました。
確認をお願い致します。

2020-11-20 09:03 UTC, kouki-iwahara reviewed
コメントしましたのでご確認ください！

2020-11-20 09:03 UTC, kouki-iwahara commented on index.html
> +      "use strict";
jsでは文字列は`""`ではなく`''`を使用する慣習がありますので修正しましょう。

2020-11-20 09:03 UTC, kouki-iwahara commented on index.html
> +      document.getElementById("button").onclick = () => {
onclickは上書きを許してしまうので、使用を避けましょう。
addEventListenerを使用すると良いです。
https://developer.mozilla.org/ja/docs/Web/API/EventTarget/addEventListener

2020-11-20 09:03 UTC, kouki-iwahara commented on index.html
> +        function chkNum(num) {
クリックされるごとに関数が宣言されてしまうので、クリックイベントの外に出しましょう。

2020-11-20 09:03 UTC, kouki-iwahara commented on index.html
> +            Number.isInteger(num) === true &&
`Number.isInteger(num) === true`ですが、
Number.isInteger(num)の返却値がbooleanを返すので、条件としては以下のように記述しても、`Number.isInteger(num)がtrueの場合`となります。

`if(Number.isInteger(num)) {}`

58行目も同様です。

2020-11-20 09:03 UTC, kouki-iwahara commented on index.html
> +            num != ""
等価演算子は`==`ではなく`===`を使用しましょう。
https://developer.mozilla.org/ja/docs/Web/JavaScript/Reference/Operators/Strict_equality

2020-11-20 09:03 UTC, kouki-iwahara commented on index.html
> +            return true;
条件がすでにbooleanを返却するものなので、「条件がtrueの時trueを返す」のように処理が被ってしまっています。
なので、
```
function chkNum(num) {
　return Number.isInteger(num) && num > 0 ,,,,,,
}
```
のように、条件の結果をそのままreturnする記述にすると良いです。

2020-11-20 22:34 UTC, tamaji22 commented on index.html
> +      'use strict';
"から'へ変更しました。

2020-11-20 22:34 UTC, tamaji22 commented on index.html
> +      function chkNum(num) {
関数の宣言をクリックイベント内で宣言していたので、外に移動しました。

2020-11-20 22:44 UTC, tamaji22 commented on index.html
> +      document.getElementById('button').addEventListener('click', () => {
`onclick`を`addEventListener`に変更。
基本的には`addEventLister`を使用したほうがいいのでしょうか？
使い分けがよくわかりません。

2020-11-20 22:46 UTC, tamaji22 commented on index.html
> +        return Number.isInteger(num) && num > 0 && num !== null && num !== '';
`Number.isInteger(num) === true`としていたので、`Number.isInteger(num)`と修正しました。

2020-11-20 22:48 UTC, tamaji22 commented on index.html
> +        return Number.isInteger(num) && num > 0 && num !== null && num !== '';
`num != null && num != ''`と等価演算を使用していたので、`num !== null && num !== ''`厳密等価演算に修正しました。

2020-11-20 22:55 UTC, tamaji22 commented on index.html
> +        return Number.isInteger(num) && num > 0 && num !== null && num !== '';
```
function chkNum(num) {
    if (
        Number.isInteger(num) === true &&
        num > 0 &&
        num != null &&
        num != ""
      ) {
        return true;
      } else {
        return false;
      }
}
```
としていたのを
`return Number.isInteger(num) && num > 0 && num !== null && num !== '';`として
処理が被らないように直接結果を返すようにしました。

2020-11-20 22:56 UTC, tamaji22 commented
指摘された点を修正しました。
確認をお願い致します。

2020-11-21 12:24 UTC, myzktkyk commented on index.html
> +      document.getElementById('button').addEventListener('click', () => {
@tamaji22 
>基本的にはaddEventListerを使用したほうがいいのでしょうか？

その通りです。
以下に詳しくまとまっていますので是非ご覧になってみてください！
https://holygrail.hatenablog.com/entry/20080515/1210861489

2020-11-21 12:51 UTC, myzktkyk requested changes
1点指摘をしております。

2020-11-21 12:51 UTC, myzktkyk commented on index.html
> +      function chkNum(num) {
この関数の名前について。
気持ちはとてもわかるのですが、あえて厳しいことを言うと…
「入力値のどう言った点をチェックするのか」
「チェックした結果、何が戻り値として戻されるのか」
と言うことがいまいちわからない名前になってしまっています。
この関数は入力値が入力されており、かつ整数であることを boolean で返すのですから以下のような名前はいかがでしょうか？

```suggestion
      function isNotNullAndInteger(num) {
```

2020-11-21 13:03 UTC, tamaji22 commented
関数名を`chkNum`から提案頂いた`isNotNullAndInteger`へ変更しました。
確認をお願い致します。

2020-11-29 02:13 UTC, merged